 export let body = {
     "Before": {
         "ProspectID": "468eeaf9-2bc4-40e6-8aeb-e393191c37fa",
         "ProspectAutoId": "26665",
         "FirstName": "1",
         "LastName": null,
         "EmailAddress": "123@111.cc",
         "Phone": null,
         "Mobile": null,
         "Source": "Contact Form 7",
         "SourceMedium": "",
         "SourceCampaign": "",
         "ProspectStage": "Opportunity",
         "Score": "0",
         "EngagementScore": "0",
         "ProspectActivityName_Max": "Lead Capture",
         "ProspectActivityDate_Max": "2020-11-20 11:38:49",
         "OwnerId": "6ba64831-b1c1-11e4-981b-22000a9700b4",
         "ModifiedOn": "2021-10-11 17:15:58",
         "mx_State": null,
         "mx_Country": null,
         "StageRottingFlagStatus": null,
         "StageRottingFlagMessage": null,
         "StageRottingFlagModifiedOn": null,
         "StageRottingFlagLevel": null,
         "QualityScore01": null,
         "OwnerIdEmailAddress": "rizwanali@3ee13.com"
     },
     "After": {
         "ProspectID": "468eeaf9-2bc4-40e6-8aeb-e393191c37fa",
         "ProspectAutoId": "26665",
         "FirstName": "1",
         "LastName": null,
         "EmailAddress": "123@111.cc",
         "Phone": null,
         "Mobile": null,
         "Source": "Contact Form 7",
         "SourceMedium": "",
         "SourceCampaign": "",
         "ProspectStage": "Prospect",
         "Score": "0",
         "EngagementScore": "0",
         "ProspectActivityName_Max": "Lead Capture",
         "ProspectActivityDate_Max": "2020-11-20 11:38:49",
         "OwnerId": "6ba64831-b1c1-11e4-981b-22000a9700b4",
         "ModifiedOn": "2021-10-11 17:16:05",
         "mx_State": null,
         "mx_Country": null,
         "StageRottingFlagStatus": null,
         "StageRottingFlagMessage": null,
         "StageRottingFlagModifiedOn": null,
         "StageRottingFlagLevel": null,
         "QualityScore01": null,
         "OwnerIdEmailAddress": "rizwanali@3ee13.com"
     },
     "Current": {
         "OptedOutDate": null,
         "ProspectActivityName_Min": null,
         "ProspectID": "468eeaf9-2bc4-40e6-8aeb-e393191c37fa",
         "ProspectAutoId": "26665",
         "FirstName": "1",
         "LastName": null,
         "EmailAddress": "123@111.cc",
         "Company": null,
         "Origin": "Contact Form 7",
         "Phone": null,
         "Mobile": null,
         "Fax": null,
         "Website": null,
         "TimeZone": null,
         "Region": null,
         "JobTitle": null,
         "Source": "Contact Form 7",
         "SourceMedium": "",
         "Notes": null,
         "SourceCampaign": "",
         "SourceContent": "",
         "DoNotEmail": "0",
         "DoNotCall": "0",
         "ProspectStage": "Prospect",
         "Grade": null,
         "Score": "0",
         "Revenue": "234",
         "EngagementScore": "0",
         "TotalVisits": "0",
         "PageViewsPerVisit": "0",
         "AvgTimePerVisit": "0",
         "RelatedProspectId": null,
         "ProspectActivityId_Min": "8f0abe72-887f-4b7c-a492-536a8eb8fd13",
         "ProspectActivityDate_Min": "2020-11-20 11:38:35",
         "Web_Referrer": "",
         "Web_RefKeyword": "",
         "ProspectActivityId_Max": "0b9ce6ca-5c43-4172-8004-362f354bdb4b",
         "ProspectActivityName_Max": "Lead Capture",
         "ProspectActivityDate_Max": "2020-11-20 11:38:49",
         "ImportTransactionId": null,
         "RelatedLandingPageId": null,
         "FirstLandingPageSubmissionId": null,
         "FirstLandingPageSubmissionDate": null,
         "OwnerId": "6ba64831-b1c1-11e4-981b-22000a9700b4",
         "CreatedBy": "6ba64831-b1c1-11e4-981b-22000a9700b4",
         "CreatedOn": "2020-11-20 11:38:35",
         "ModifiedBy": "6ba64831-b1c1-11e4-981b-22000a9700b4",
         "ModifiedOn": "2021-10-11 17:16:05",
         "LeadConversionDate": "2020-11-20 11:38:35",
         "StatusCode": "0",
         "StatusReason": "0",
         "DeletionStatusCode": "0",
         "IsLead": "1",
         "mx_Street1": null,
         "mx_Street2": null,
         "mx_City": null,
         "mx_State": null,
         "mx_Country": null,
         "mx_Zip": null,
         "mx_Geography": null,
         "mx_DOB": null,
         "mx_Anniversary": null,
         "mx_FaceBookURL": null,
         "mx_TwitterURL": null,
         "mx_LinkedInURL": null,
         "JobTitleLevel": null,
         "mx_Your_Intrest": null,
         "mx_Lead_Date": null,
         "mx_lead_Id": null,
         "mx_State_List": null,
         "mx_StateCus": null,
         "mx_StateCs": null,
         "mx_withothers": null,
         "mx_PhoneA_NuMBER": null,
         "mx_LeadHidden": null,
         "mx_Source_term": null,
         "mx_ModifiedTime": null,
         "mx_CreationTime": null,
         "mx_Budget_Min": null,
         "mx_Budget_Max": null,
         "mx_Email_Source": null,
         "mx_Interested_in": null,
         "mx_Prefer": null,
         "mx_Project": null,
         "mx_Want_Property": null,
         "mx_Wants_within": null,
         "mx_Website_Source": null,
         "mx_Intereted_in": null,
         "mx_date_and_time": null,
         "mx_datte": null,
         "mx_dandt": null,
         "mx_Engagement_Score_Custom": null,
         "mx_CR_Child_First_Name": null,
         "mx_CR_Entry_Year_Level": null,
         "mx_CR_Entry_Year": null,
         "mx_Contact_Suburb": null,
         "LastModifiedOn": "2021-10-11 17:16:05",
         "mx_Multi_Select": "2",
         "mx_Student_Name": null,
         "mx_Schedule": null,
         "mx_Source_MarketPlace": null,
         "mx_Secondary_Email": null,
         "mx_TimeRange": null,
         "mx_Dependent": null,
         "mx_Select_Dep": null,
         "mx_Online_Lead_Type": null,
         "mx_Regions": null,
         "mx_uid": null,
         "mx_Date_of_birth": null,
         "mx_testdemo": null,
         "mx_multi": null,
         "NotableEvent": "Modified",
         "NotableEventdate": "2021-10-11 17:16:05",
         "SourceReferrer": "",
         "LastVisitDate": "2020-11-20 11:38:49",
         "LeadAge": "325",
         "PhotoUrl": null,
         "StageRottingFlagStatus": null,
         "StageRottingFlagMessage": null,
         "StageRottingFlagModifiedOn": null,
         "StageRottingFlagAdditionalInfo": null,
         "StageRottingFlagLevel": null,
         "MailingPreferences": null,
         "DoNotTrack": null,
         "Latitude": null,
         "Longitude": null,
         "TwitterId": null,
         "FacebookId": null,
         "LinkedInId": null,
         "SkypeId": null,
         "GTalkId": null,
         "GooglePlusId": null,
         "QualityScore01": null,
         "CurrentOptInStatus": null,
         "OptInDate": null,
         "OptInDetails": null,
         "LastOptInEmailSentDate": null,
         "ConversionReferrerURL": null,
         "SourceReferrerURL": null,
         "SourceIPAddress": null,
         "LeadLastModifiedOn": "2021-10-11 17:16:05",
         "OwnerIdName": "rizwan ali",
         "OwnerIdEmailAddress": "rizwanali@3ee13.com",
         "Groups": "",
         "CreatedByName": "rizwan ali",
         "ModifiedByName": "rizwan ali",
         "Total": "1",
         "FlagLevel": null,
         "FlagAdditionalInfo": null,
         "FlagStatus": null,
         "FlagMessage": null,
         "FlaggingModifiedOn": null,
         "CanUpdate": "true"
     }
 };